# Generated by Django 5.0.3 on 2024-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='em_equipamento',
            new_name='ativo',
        ),
    ]
