# Generated by Django 5.0.3 on 2024-04-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_rename_em_equipamento_exercicio_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='ativo',
            new_name='esta_ativo',
        ),
    ]
