# Generated by Django 5.0.3 on 2024-04-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_rename_esta_ativo_exercicio_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='ativo',
            new_name='esta_ativo',
        ),
    ]
