# Generated by Django 5.0.3 on 2024-04-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0005_rename_ativo_exercicio_esta_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='esta_ativo',
            new_name='ativo',
        ),
    ]
